<?php

namespace ContainerO8InwSE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V5s_1kZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v5s.1kZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v5s.1kZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gifRepository' => ['privates', 'App\\Repository\\GifRepository', 'getGifRepositoryService', true],
        ], [
            'gifRepository' => 'App\\Repository\\GifRepository',
        ]);
    }
}
