<?php

namespace ContainerO8InwSE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FBnCD2yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FBnCD2y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FBnCD2y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'quiz' => ['privates', '.errored..service_locator.FBnCD2y.App\\Entity\\Quiz', NULL, 'Cannot autowire service ".service_locator.FBnCD2y": it references class "App\\Entity\\Quiz" but no such service exists.'],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'paginator' => '?',
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'quiz' => 'App\\Entity\\Quiz',
            'quizRepository' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
