<?php

namespace ContainerO8InwSE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomNamer_GifImagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Naming\CustomNamer.gif_images' shared autowired service.
     *
     * @return \App\Naming\CustomNamer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Naming/NamerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Naming/CustomNamer.php';

        return $container->services['App\\Naming\\CustomNamer.gif_images'] = new \App\Naming\CustomNamer('rename_picture');
    }
}
