<?php

namespace ContainerO8InwSE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FrontOffice\UserController' shared autowired service.
     *
     * @return \App\Controller\FrontOffice\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FrontOffice/UserController.php';

        $container->services['App\\Controller\\FrontOffice\\UserController'] = $instance = new \App\Controller\FrontOffice\UserController(($container->privates['App\\Repository\\PlayRepository'] ?? $container->load('getPlayRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\FrontOffice\\UserController', $container));

        return $instance;
    }
}
