<?php

namespace ContainerR5Az8HF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGifBackOfficeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BackOffice\GifBackOfficeController' shared autowired service.
     *
     * @return \App\Controller\BackOffice\GifBackOfficeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BackOffice/GifBackOfficeController.php';

        $container->services['App\\Controller\\BackOffice\\GifBackOfficeController'] = $instance = new \App\Controller\BackOffice\GifBackOfficeController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\BackOffice\\GifBackOfficeController', $container));

        return $instance;
    }
}
