<?php

namespace ContainerR5Az8HF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRewardFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RewardFormType' shared autowired service.
     *
     * @return \App\Form\RewardFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RewardFormType.php';

        return $container->privates['App\\Form\\RewardFormType'] = new \App\Form\RewardFormType();
    }
}
