<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO8InwSE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO8InwSE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO8InwSE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO8InwSE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO8InwSE\App_KernelDevDebugContainer([
    'container.build_hash' => 'O8InwSE',
    'container.build_id' => 'b8821f54',
    'container.build_time' => 1703091301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO8InwSE');
